### PR TITLE
Update highline

### PR DESCRIPTION
**Pull request by belousovAV**
Update highline gem to fix ruby 3.3 [warning](https://github.com/JEG2/highline/blob/master/Changelog.md#300--2024-01-05)

Increase ruby version to match highline gem requirements

### CODE REVIEW

**Comment by lacostej** [comment]
I would love commander to relax its dependency on highline, so that we could use version 3.0.0 or later in fastlane, but we wouldn't be able to upgrade to a version that forces ruby 3.0 yet.

**Review by ggilder — APPROVED** [review]
LGTM!

**Comment by ggilder** [comment]
Thanks for doing this. Since the version requirement is a breaking change for older versions of Ruby, I'm going to bump commander up a major version as well to 5.0.0. I'll push that later today.

**Comment by ggilder** [comment]
Published! https://rubygems.org/gems/commander

**Comment by ggilder** [comment]
@lacostej let me know if this works for fastlane; don't know if you're planning to keep supporting ruby < 3.0 since those are EOL... I _think_ you could change fastlane's dependency on commander to `>= 4.6.0` to allow either the previous version, or the new version when running ruby 3.

**Pull request merged**
